# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diff.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 50, 100, 40))
        self.label.setStyleSheet("color: rgb(85, 255, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 50, 130, 40))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 240, 130, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 240, 100, 40))
        self.label_2.setStyleSheet("color: rgb(85, 255, 0);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(50, 340, 131, 40))
        # self.label_3.setObjectName("label_3")
        # self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        # self.comboBox.setGeometry(QtCore.QRect(170, 350, 69, 22))
        # self.comboBox.setObjectName("comboBox")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        # self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 90, 161, 71))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 420, 161, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 280, 161, 71))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        # self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        # self.comboBox_2.setGeometry(QtCore.QRect(170, 200, 69, 22))
        # self.comboBox_2.setObjectName("comboBox_2")
        # self.comboBox_2.addItem("")
        # self.comboBox_2.addItem("")
        # self.comboBox_2.setItemText(1, "")
        # self.comboBox_2.addItem("")
        # self.comboBox_2.addItem("")
        # self.label_6 = QtWidgets.QLabel(self.centralwidget)
        # self.label_6.setGeometry(QtCore.QRect(50, 190, 131, 40))
        # self.label_6.setObjectName("label_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(490, 450, 191, 31))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 895, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "选择源csv文件"))
        self.pushButton_2.setText(_translate("MainWindow", "选择目标csv文件"))
        # self.label_3.setText(_translate("MainWindow", "设置分割符："))
        # self.comboBox.setItemText(0, _translate("MainWindow", ","))
        # self.comboBox.setItemText(1, _translate("MainWindow", " "))
        # self.comboBox.setItemText(2, _translate("MainWindow", ";"))
        # self.comboBox.setItemText(3, _translate("MainWindow", "|"))
        self.pushButton_3.setText(_translate("MainWindow", "start"))
        # self.comboBox_2.setItemText(0, _translate("MainWindow", ","))
        # self.comboBox_2.setItemText(2, _translate("MainWindow", ";"))
        # self.comboBox_2.setItemText(3, _translate("MainWindow", "|"))
        # self.label_6.setText(_translate("MainWindow", "设置分割符："))
